#!/usr/bin/env python3
import os
import re
import json
from datetime import datetime
from pathlib import Path

def get_version_info():
    """Read version information from VERSION file"""
    version_file = Path(__file__).parent.parent.parent / 'VERSION'
    try:
        with open(version_file) as f:
            version = f.read().strip()
            
            # Validate version format
            if not re.match(r'^\d+\.\d+\.\d+$', version):
                raise ValueError(f"Invalid version format in VERSION file: {version}")
            
            return version
    except Exception as e:
        print(f"Error reading VERSION file: {str(e)}")
        print("Please create a VERSION file with format MAJOR.MINOR.PATCH (e.g. 1.0.0)")
        raise

def generate_build_metadata():
    """Generate build metadata for version string"""
    now = datetime.utcnow()
    return {
        'build_date': now.strftime("%Y-%m-%d"),
        'build_time': now.strftime("%H:%M:%S"),
        'build_number': now.strftime("%Y%m%d%H%M"),
        'git_sha': os.getenv('GITHUB_SHA', 'local')[:7]
    }

def generate_version_files(version, build_info):
    """Generate all version-related files"""
    project_root = Path(__file__).parent.parent.parent
    include_dir = project_root / 'include'
    include_dir.mkdir(exist_ok=True)
    
    # Generate C++ version header
    header_content = f"""// Auto-generated by leeno_version_generator.py
#ifndef LEENO_VERSION_H
#define LEENO_VERSION_H

#define LEENO_VERSION_MAJOR {version.split('.')[0]}
#define LEENO_VERSION_MINOR {version.split('.')[1]}
#define LEENO_VERSION_PATCH {version.split('.')[2]}
#define LEENO_VERSION_STRING "{version}"
#define LEENO_BUILD_NUMBER "{build_info['build_number']}"
#define LEENO_BUILD_DATE "{build_info['build_date']}"
#define LEENO_BUILD_TIME "{build_info['build_time']}"
#define LEENO_GIT_SHA "{build_info['git_sha']}"

#endif // LEENO_VERSION_H
"""
    
    with open(include_dir / 'version.h', 'w') as f:
        f.write(header_content)
    
    # Generate version.json for other tools
    version_data = {
        'version': version,
        **build_info
    }
    
    with open(project_root / 'version.json', 'w') as f:
        json.dump(version_data, f, indent=2)

def main():
    try:
        print("Generating version information...")
        
        version = get_version_info()
        build_info = generate_build_metadata()
        
        print(f"Version: {version}")
        print(f"Build Number: {build_info['build_number']}")
        print(f"Git SHA: {build_info['git_sha']}")
        
        generate_version_files(version, build_info)
        print("Version files generated successfully")
        
    except Exception as e:
        print(f"Error: {str(e)}")
        return 1
    
    return 0

if __name__ == "__main__":
    exit(main())