// Auto-generated
#ifndef LEENO_VERSION_H
#define LEENO_VERSION_H
#define LEENO_VERSION_FULL "LeenO-3.25.0.32-TESTING-20260422"
#define LEENO_VERSION_MAJOR 3
#define LEENO_VERSION_MINOR 25
#define LEENO_VERSION_PATCH 0
#define LEENO_BUILD_NUMBER "32"
#define LEENO_BUILD_DATE "2026-04-22"
#define LEENO_GIT_SHA "local"
#endif
