// Auto-generated
#ifndef LEENO_VERSION_H
#define LEENO_VERSION_H
#define LEENO_VERSION_FULL "LeenO-3.26.0.14-TESTING-20260526"
#define LEENO_VERSION_MAJOR 3
#define LEENO_VERSION_MINOR 26
#define LEENO_VERSION_PATCH 0
#define LEENO_BUILD_NUMBER "14"
#define LEENO_BUILD_DATE "2026-05-26"
#define LEENO_GIT_SHA "local"
#endif
